title: "Researca | Blog"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/researca.svg'
favicon: 'assets/images/favicon.svg'
author: Constant
paginate: 30
#disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
researca_url: https://researca.com/app/signin
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  constant:
    name: Constant
    display_name: Constant
    avatar: 'assets/images/sal.png'
    email: contact@researca.com
    web: https://telary.io
    twitter: https://twitter.com/researca
    description: "Developper of Researca"

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom
  reddit: https://reddit.com/r/researca

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives